name: Deploy

on:
  push:
    branches: ['master']

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install project
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  deploy:
    needs: eslint
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install project
        run: npm ci

      - name: Build static assets
        run: npm run build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - uses: actions/configure-pages@v3

      - uses: actions/deploy-pages@v2
        id: deployment
