name: Lint

on: [push, workflow_call]

jobs:
  eslint:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean install project
        run: npm ci

      - name: Run ESLint
        run: npm run lint
